---
roles:
  master:
    private_networks:
      - ip: '0.0.0.0'
        auto_network: true
    providers:
      - type: virtualbox
        customize:
          - [modifyvm, !ruby/sym id, '--memory', 4096]
          - [modifyvm, !ruby/sym id, '--ioapic', 'on']
          - [modifyvm, !ruby/sym id, '--cpus', '2']
    synced_folders:
      - host_path:  '.files'
        guest_path: '/opt/tse-files'
    provisioners:
      - type: shell
        inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"
      - {type: hosts, sync_hosts: true}
      - type: pe_bootstrap
        role: !ruby/sym master
        autosign:
          - '*.vm'
          - '*.demo'
        answer_extras:
          - '"puppet_enterprise::use_application_services": true'
          - '"puppet_enterprise::profile::master::r10k_remote": "https://github.com/ncorrare/blueshift-control"'
          - '"puppet_enterprise::profile::master::r10k_private_key": "/dev/null"'
          - '"puppet_enterprise::profile::master::code_manager_auto_configure": true'
          - '"puppet_enterprise::profile::master::check_for_updates": false'

      - type: shell
        path: "scripts/bootstrap.sh"


  windows_agent:
    communicator: winrm
    forwarded_ports:
          - { guest: 5985, host: 35985, auto_correct: true }
          - { guest: 3389, host: 33389, auto_correct: true }
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    provisioners:
      - {type: hosts, sync_hosts: true}
      - type: shell
        inline: 'Set-ItemProperty -Path "HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System" -Name "EnableLUA" -Value "0"'
      # The reload is important. It needs to happen for the name, domain, and
      # registry changes to take effect.
      - type: reload
      # Install the windows puppet agent using a PowerShell script. The
      # install_agent.ps1 script will set the agent certname it reads from
      # the system. The hosts provisioner should have configured these things
      # prior to the reboot.
      - type: shell
        path: "scripts/install_agent.ps1"
    synced_folders:
      - host_path:  '.files'
        guest_path: 'c:/seteam-files'

  posix_agent:
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    provisioners:
      - {type: shell, inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"}
      - {type: hosts, sync_hosts: true}
      - type: shell
        inline: |-
          curl -sk https://master.inf.puppet.vm:8140/packages/current/install.bash | /bin/bash

  darwin_agent:
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}

  posix_noagent:
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    provisioners:
      - {type: shell, inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"}
      - {type: hosts, sync_hosts: true}
